export { default as Navbar } from "./Navbar"
export { default as CustomInput } from "./CustomInput"
export { default as HomeIcon } from "./HomeIcon" 
export { default as CaloriesResult } from "./CaloriesResult"
export { default as AnimatedPage } from "./AnimatedPage"
export { default as AnimatedNav } from "./AnimatedNav"